### PR TITLE
[DRAFT] First step to resolve #519 by replacing basic auth with JWT

### LINKED ISSUE #519: More flexible authentication
**Is your feature request related to a problem? Please describe.**

We're using OIDC for authentication throughout the applications and additionally Traefik middleware (Remote-User, Remote-Groups, Remote-Email headers) for dumb applications which don't support OIDC. With current ZincSearch I am back to managing users/passwords in the application.

**Describe the solution you'd like**

OIDC has group claim. One option is to support mapping OIDC groups to ACL-s in Zinc (admin vs read-only would be good start)

**Describe alternatives you've considered**

Alternative solution would use JWT tokens which defines the scope (search begin timestamp, search end timestamp and possibly field filters). The benefit of this approach is that third parties can implement their own authzn and ACL logic and most importantly this approach would allow sharing log snippets with external parties who don't even have user accounts, a'la think Pastebin kind of behaviour.

**Additional context**
Somewhat related to #518

### PR DESCRIPTION
**Pull request by jonasgeiregat**
Step one towards allow integrating OIDC is having a stateless authentication available.

This PR replaces basic auth with a JWT implementation.

#519

### CODE REVIEW

**Comment by hengfeiyang** [comment]
Thanks, i will review it soon

**Comment by hengfeiyang** [comment]
I tested this PR, It has a problem that it dropped HTTP Basic Auth. But this will cause a problem that can't compatible with old versions, all users need to update the API for ingesting data.

I think we still need HTTP Basic Auth.

@prabhatsharma What do you think?

**Comment by jonasgeiregat** [comment]
> I tested this PR, It has a problem that it dropped HTTP Basic Auth. But this will cause a problem that can't compatible with old versions, all users need to update the API for ingesting data.
> 
> I think we still need HTTP Basic Auth.

Correct I've updated the PR to bring back Basic Auth support. The website now only relies on JWT authentication so this will allow us to implement OIDC support as a next step.

**Comment by hengfeiyang** [comment]
@jonasgeiregat I have two questions:

1. `handlers/auth/login.go: Login` function is a handler for route, it shouldn't return something, maybe you need a middleware for auth, you should create a new method for middleware, not use this method.
2. `handlers/auth/security.go` this files looks it's a auth middleware for jit, you should move it to `pkg/routes/` directory.

Thanks.

**Comment by jonasgeiregat** [comment]
> 1. `handlers/auth/login.go: Login` function is a handler for route, it shouldn't return something, maybe you need a middleware for auth, you should create a new method for middleware, not use this method.

It's a callback function used by `gin-jwt` with the following signature: `func(c *gin.Context) (interface{}, error)`

I know it comes across as confusing that it has the swagger API documentation on it while it's not a pure handler for route. But, this way the login API will be visible in the documenation.

> 2. `handlers/auth/security.go` this files looks it's a auth middleware for jit, you should move it to `pkg/routes/` directory.

Correct I moved the file.

**Comment by hengfeiyang** [comment]
> It's a callback function used by gin-jwt with the following signature: func(c *gin.Context) (interface{}, error)
> I know it comes across as confusing that it has the swagger API documentation on it while it's not a pure handler for route. But, this way the login API will be visible in the documentation.

I known, but I think we still let code readable, you can wrap it. like middleware `handleBasicAuth`

**Comment by hengfeiyang** [comment]
This PR has 2 problems:

- you need to format `import` for go files.
- I saw used cookie for auth, it's not a good idea, I think we should use localStorage in frontend. and we should use pass token in header like this:

```
Authorization: Bearer eyJhbGciOiJIUzI1NiI...
```

**Comment by jonasgeiregat** [comment]
>

**Comment by jonasgeiregat** [comment]
Closed by accident.

**Comment by jonasgeiregat** [comment]
> * I saw used cookie for auth, it's not a good idea, I think we should use localStorage in frontend. and we should pass token in header like this:

Putting the token in localStorage makes the app prone to XSS, the cookie is protected because it's a httpOnly cookie.
Putting the token in the header makes it prone to CSRF with cookies this is protected by using the Access-Control-Allow-Origin header.

**Comment by hengfeiyang** [comment]
You set cookie domain is localhost, if use other domain, it can't work.

**Comment by jonasgeiregat** [comment]
> You set cookie domain is localhost, if use other domain, it can't work.

Yes localhost by default but this can be overridden by the ZINC_PUBLIC_HOSTNAME and others. See AllowOrigins settings in the routes.

**Comment by hengfeiyang** [comment]
Why we need set the ENV, can it work without set the hostname?

**Comment by jonasgeiregat** [comment]
I've been thinking about this and, although I consider it less secure, I will refactor it to storing the jwt token in a HTTP header and local-storage. Would that be acceptable ?

**Pull request closed without merging**
