### PR TITLE
 Support for go1.21

### PR DESCRIPTION
**Pull request by gaby**
- Bump minimum go version to 1.21
- Update github-actions
- Update go dependencies
- Remove deprecated ioutils.Discard
- Bump NodeJs to 18.18.2

### CODE REVIEW

**Comment by gaby** [comment]
@hengfeiyang I had no idea how to run the unit-tests locally, so i'm hoping they all run fine in the CI

**Comment by gaby** [comment]
Question, does the CI need to run in AWS? Can it be switched to Github? It would be so much easier to debug/breakdown

**Comment by hengfeiyang** [comment]
@gaby The CI failed, you can run these code in your local: https://github.com/zincsearch/zincsearch/blob/main/buildspec-pr.yml#L29C1-L40C22

**Comment by gaby** [comment]
@hengfeiyang Will do, seems like golangci-lint needs to be updated. I'm running this locally now to see what the issue is. Thanks!

**Review by hengfeiyang — APPROVED** [review]

**Pull request merged**
